services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/indofrench
    volumes:
      - .:/app:cached
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    user: "1001:1001"  # Utiliser l'utilisateur nextjs
    
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: indofrench
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata_dev: 
